// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.context;

namespace backend.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20210725180349_movies")]
    partial class movies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("backend.context.Movie", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("RatingCount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("backend.context.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("backend.context.UserRating", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("MovieId")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRating");
                });

            modelBuilder.Entity("backend.context.UserRating", b =>
                {
                    b.HasOne("backend.context.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.HasOne("backend.context.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
